/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotel.ui;

import hotel.classes.Room;
import hotel.classes.RoomFare;
import hotel.databaseOperation.RoomDb;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;

import javax.swing.JOptionPane;


import net.proteanit.sql.DbUtils;

/**
 *
 * @author Faysal Ahmed
 */
public class RoomPanel extends javax.swing.JDialog {

    /**
     * Creates new form RoomPanel
     */
    
    RoomFare roomType = new RoomFare();
    Room room =new Room(""); 
    
    ResultSet result;
    ArrayList<String> roomClass = new ArrayList<>();
    
    RoomDb roomdb = new RoomDb();
    public RoomPanel(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.getContentPane().setBackground(new Color(241,241,242));
        populateCombo();
        populateRoomTable();
        populateRoomTypeTable();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPane = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableRooms = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        checkPhone = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        tfRoomNo = new javax.swing.JTextField();
        comboRoomType = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        btnEdit = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        checkTv = new javax.swing.JCheckBox();
        checkWifi = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        checkGizer = new javax.swing.JCheckBox();
        tfRoomID = new javax.swing.JTextField();
        btnDelete = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        tfBeds = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnAddRoomType = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnDeleteRoomType = new javax.swing.JButton();
        tf_roomType = new javax.swing.JTextField();
        tfPrice = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnEditRoomType = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableRoomType = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tableRooms.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableRooms.setToolTipText("");
        tableRooms.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_roomsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableRooms);

        jPanel4.setBackground(new java.awt.Color(230, 231, 232));

        checkPhone.setText("Phone Service");

        jLabel3.setText("Beds");

        jLabel1.setText("Room ID");

        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/EditButton.png"))); // NOI18N
        btnEdit.setEnabled(false);
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });

        jLabel6.setText("Category");

        checkTv.setText("TV");

        checkWifi.setText("WIFI");
        checkWifi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_wifiActionPerformed(evt);
            }
        });

        jLabel2.setText("Room No");

        checkGizer.setText("Gizer");

        tfRoomID.setEditable(false);
        tfRoomID.setBackground(new java.awt.Color(204, 204, 255));

        btnDelete.setBackground(new java.awt.Color(255, 0, 0));
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/DeleteButton.png"))); // NOI18N
        btnDelete.setEnabled(false);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/DefaultButton.png"))); // NOI18N
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(comboRoomType, 0, 100, Short.MAX_VALUE)
                            .addComponent(tfRoomID)
                            .addComponent(tfRoomNo)
                            .addComponent(tfBeds)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(checkTv, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(checkPhone))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(checkWifi, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(checkGizer, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfRoomID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfRoomNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfBeds, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(comboRoomType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkTv)
                    .addComponent(checkPhone))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkGizer)
                    .addComponent(checkWifi))
                .addGap(18, 18, 18)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106))
        );

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/reset.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 677, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(191, 191, 191)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabbedPane.addTab("Room Information", jPanel1);

        jPanel3.setBackground(new java.awt.Color(230, 231, 232));

        btnAddRoomType.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/DefaultButton.png"))); // NOI18N
        btnAddRoomType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addRoomTypeActionPerformed(evt);
            }
        });

        jLabel5.setText("Price");

        btnDeleteRoomType.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/DeleteButton.png"))); // NOI18N
        btnDeleteRoomType.setEnabled(false);
        btnDeleteRoomType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteRoomTypeActionPerformed(evt);
            }
        });

        tfPrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_priceKeyTyped(evt);
            }
        });

        jLabel4.setText("Room Type");

        btnEditRoomType.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/EditButton.png"))); // NOI18N
        btnEditRoomType.setEnabled(false);
        btnEditRoomType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editRoomTypeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tf_roomType, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tfPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnEditRoomType, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAddRoomType, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDeleteRoomType, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(123, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_roomType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(tfPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(btnAddRoomType, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEditRoomType, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDeleteRoomType, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        tableRoomType.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableRoomType.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_roomTypeMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableRoomType);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(256, 256, 256)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(128, Short.MAX_VALUE))
        );

        tabbedPane.addTab("Room Class", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_addRoomTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addRoomTypeActionPerformed
        roomTypeObjectCreation();
        roomdb.insertRoomType(roomType);
        populateRoomTypeTable();
        
    }//GEN-LAST:event_btn_addRoomTypeActionPerformed

    private void populateCombo()
    {
        try {
            ResultSet rs = roomdb.getRoomType();
            while(rs.next())
            {
                roomClass.add(rs.getString("type"));
                comboRoomType.addItem(rs.getString("type"));
            }
          
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Combo Fillup failed");
        }
    
    }

    // Method to populate the room type table with data from the database
    private void populateRoomTypeTable() {
        // Uncommented for debugging: Outputs the selected index of the tab in the tabbed pane
        // System.out.println(tabbedPane.getSelectedIndex());

        // Fetch the list of room types from the database
        result = roomdb.getRoomType();

        // Set the table model with the data fetched from the database,
        // converting the ResultSet to a table model that the table can display
        tableRoomType.setModel(DbUtils.resultSetToTableModel(result));

        // Clear any cached data from the database after fetching the room types
        roomdb.flushAll();
    }


    // Method to populate the room table with data from the database
    private void populateRoomTable() {
        // Fetch the list of rooms from the database
        result = roomdb.getRooms();

        // Set the table model with the data fetched from the database,
        // converting the ResultSet to a table model that the table can display
        tableRooms.setModel(DbUtils.resultSetToTableModel(result));

        // Clear any cached data from the database after fetching the rooms
        roomdb.flushAll();
    }


    /**
     * Ensures only numeric input (digits) is allowed in the price text field.
     *
     * This method is triggered whenever a key is typed in the tf_price field.
     * It allows only digits, backspace, and delete keys.
     * Any other character input is consumed (ignored).
     *
     * @param evt The KeyEvent triggered by typing into the tf_price field.
     */
    private void tf_priceKeyTyped(java.awt.event.KeyEvent evt) {
        char c = evt.getKeyChar();

        // Allow only digits, backspace, and delete
        if (!(Character.isDigit(c) || c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE)) {
            evt.consume(); // Ignore invalid input
        }
    }


    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
       
       roomObjectCreation();
       roomdb.insertRoom(room);
       populateRoomTable();
       clearRoomPanel();
        
        
    }//GEN-LAST:event_btn_addActionPerformed

    private void btn_editRoomTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editRoomTypeActionPerformed
        roomTypeObjectCreation();
        roomdb.updateRoomType(roomType);
        populateRoomTypeTable();
        btnEditRoomType.setEnabled(false);
        btnAddRoomType.setEnabled(true);
        
        
    }//GEN-LAST:event_btn_editRoomTypeActionPerformed

    private void table_roomTypeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_roomTypeMouseClicked
        roomType = new RoomFare();
        int row = tableRoomType.getSelectedRow();
        displayToTextField(row);
        btnAddRoomType.setEnabled(false);
        btnEditRoomType.setEnabled(true);
        btnDeleteRoomType.setEnabled(true);
    }//GEN-LAST:event_table_roomTypeMouseClicked

    private void table_roomsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_roomsMouseClicked
        room = new Room(null);
        btnEdit.setEnabled(true);
        btnDelete.setEnabled(true);
        btnAdd.setEnabled(false);
        int row = tableRooms.getSelectedRow();
        displayToRoomTextField(row);
       // System.out.println(tableRooms.getValueAt(row, 1)+"");
        //System.out.println(">>>>>>> "+row );
        
    }//GEN-LAST:event_table_roomsMouseClicked

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        roomObjectCreation();
        roomdb.updateRoom(room);
        populateRoomTable();
        clearRoomPanel();
        btnAdd.setEnabled(true);
        
    }//GEN-LAST:event_btn_editActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        int roomId =Integer.parseInt( tfRoomID.getText() );
        roomdb.deleteRoom(roomId);
        populateRoomTable();
        clearRoomPanel();
        btnAdd.setEnabled(true);
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        clearRoomPanel();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_deleteRoomTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteRoomTypeActionPerformed
        //int roomId =Integer.parseInt( tf_roomType.getText() );
        
        JOptionPane.showMessageDialog(null, "no method written yet");
        
    }//GEN-LAST:event_btn_deleteRoomTypeActionPerformed

    private void check_wifiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_wifiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_check_wifiActionPerformed

    /**
     * Clears all input fields and resets the room panel to its default state.
     *
     * This method is typically called when the user wants to add a new room,
     * cancel editing, or after a successful operation (insert/delete).
     * It resets the form, disables edit/delete buttons, and enables the Add button.
     */
    private void clearRoomPanel() {
        // Reset the Room object
        room = new Room(null);

        // Clear all text fields
        tfBeds.setText("");
        tfPrice.setText("");
        tfRoomID.setText("");
        tfRoomNo.setText("");
        tf_roomType.setText("");

        // Clear selection from room table
        tableRooms.clearSelection();

        // Uncheck all feature checkboxes
        checkGizer.setSelected(false);
        checkPhone.setSelected(false);
        checkTv.setSelected(false);
        checkWifi.setSelected(false);

        // Reset combo box to first item
        comboRoomType.setSelectedIndex(0);

        // Enable Add button; disable Edit and Delete
        btnAdd.setEnabled(true);
        btnEdit.setEnabled(false);
        btnDelete.setEnabled(false);
    }




    /**
     * Populates room-related text fields and checkboxes based on the selected row
     * in the tableRooms JTable.
     *
     * Retrieves values such as room ID, number, amenities (TV, WiFi, etc.),
     * and room type from the selected row and displays them in their corresponding
     * UI components.
     *
     * @param row The index of the selected row in the table.
     */
    private void displayToRoomTextField(int row) {
        var model = tableRooms.getModel();

        // Optional: guard clause for invalid row index
        if (row < 0 || row >= model.getRowCount()) return;

        tfRoomID.setText(String.valueOf(model.getValueAt(row, 0)));
        tfRoomNo.setText(String.valueOf(model.getValueAt(row, 1)));
        tfBeds.setText(String.valueOf(model.getValueAt(row, 2)));

        // Set checkbox states based on boolean string values from the table
        checkTv.setSelected(Boolean.parseBoolean(String.valueOf(model.getValueAt(row, 3))));
        checkWifi.setSelected(Boolean.parseBoolean(String.valueOf(model.getValueAt(row, 4))));
        checkGizer.setSelected(Boolean.parseBoolean(String.valueOf(model.getValueAt(row, 5))));
        checkPhone.setSelected(Boolean.parseBoolean(String.valueOf(model.getValueAt(row, 6))));

        // Set the combo box to the correct room type
        String roomType = String.valueOf(model.getValueAt(row, 7));
        comboRoomType.setSelectedIndex(getComboSearchIndex(roomType));
    }


    /**
     * Populates the text fields for room type and price based on the selected row
     * from the tableRoomType JTable.
     *
     * @param row The index of the selected row in the table.
     */
    private void displayToTextField(int row) {
        var model = tableRoomType.getModel();

        // Set the room type name from column 0
        tf_roomType.setText(String.valueOf(model.getValueAt(row, 0)));

        // Set the room price from column 1
        tfPrice.setText(String.valueOf(model.getValueAt(row, 1)));
    }


    /**
     * Returns the index of the given item in the roomClass list.
     *
     * Used to match a string value (e.g., "Deluxe", "Suite") to the correct index
     * for setting a selected item in a combo box.
     *
     * @param item The string to search for in the roomClass list.
     * @return The index of the item if found, otherwise -1.
     */
    private int getComboSearchIndex(String item) {
        // Defensive check: avoid NullPointerException if item is null
        if (item == null) return -1;

        for (int i = 0; i < roomClass.size(); i++) {
            if (item.equals(roomClass.get(i))) {
                return i;
            }
        }

        return -1; // Not found
    }


    /**
     * Initializes a Room object based on user input from the UI.
     *
     * This method populates all relevant fields of a Room, including bed count,
     * available amenities (TV, WiFi, Geyser, Phone), and its RoomFare (type).
     * If the Room ID input is not a valid integer, a default ID of -1 is used.
     */
    private void roomObjectCreation() {
        // Creates a Room with a null initial ID (presumably to be set later)
        room = new Room(null);

        // Set the room number and number of beds from text fields
        room.setRoomNo(tfRoomNo.getText().trim());

        try {
            room.setBedNumber(Integer.parseInt(tfBeds.getText().trim()));
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Invalid bed number. Please enter a number.");
        }

        // Set boolean options from checkboxes
        room.setHasTV(checkTv.isSelected());
        room.setHasWIFI(checkWifi.isSelected());
        room.setHasGizer(checkGizer.isSelected());
        room.setHasPhone(checkPhone.isSelected());

        // Set the RoomFare (type) from the combo box
        RoomFare fare = new RoomFare();
        fare.setRoomType(comboRoomType.getSelectedItem().toString());
        room.setRoomClass(fare);

        // Attempt to parse and set Room ID; if fails, use -1
        try {
            room.setRoomId(Integer.parseInt(tfRoomID.getText().trim()));
        } catch (NumberFormatException ex) {
            room.setRoomId(-1); // Indicates that room ID is not provided or invalid
        }
    }

    /**
     * Initializes a RoomFare object (roomType) based on user input from the UI.
     *
     * This method retrieves the room type name and its price per day
     * from the corresponding text fields, and populates the `roomType` object.
     *
     * Assumes that:
     * - tf_roomType contains a valid room type name (e.g., "Deluxe")
     * - tfPrice contains a valid integer price (e.g., "150")
     */
    private void roomTypeObjectCreation() {
        roomType = new RoomFare(); // Create a new RoomFare instance

        roomType.setRoomType(tf_roomType.getText().trim()); // Set the type (trimmed for safety)

        // Convert price input from string to int and set it
        try {
            int price = Integer.parseInt(tfPrice.getText().trim());
            roomType.setPricePerDay(price);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Invalid price. Please enter a valid number.");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RoomPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RoomPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RoomPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RoomPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                RoomPanel dialog = new RoomPanel(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAddRoomType;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDeleteRoomType;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnEditRoomType;
    private javax.swing.JCheckBox checkGizer;
    private javax.swing.JCheckBox checkPhone;
    private javax.swing.JCheckBox checkTv;
    private javax.swing.JCheckBox checkWifi;
    private javax.swing.JComboBox comboRoomType;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane tabbedPane;
    private javax.swing.JTable tableRoomType;
    private javax.swing.JTable tableRooms;
    private javax.swing.JTextField tfBeds;
    private javax.swing.JTextField tfPrice;
    private javax.swing.JTextField tfRoomID;
    private javax.swing.JTextField tfRoomNo;
    private javax.swing.JTextField tf_roomType;
    // End of variables declaration//GEN-END:variables

  
}
